export default {
    "login": "michi1008",
    "id": 51973693,
    "node_id": "MDQ6VXNlcjUxOTczNjkz",
    "avatar_url": "https://avatars.githubusercontent.com/u/51973693?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/michi1008",
    "html_url": "https://github.com/michi1008",
    "followers_url": "https://api.github.com/users/michi1008/followers",
    "following_url": "https://api.github.com/users/michi1008/following{/other_user}",
    "gists_url": "https://api.github.com/users/michi1008/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/michi1008/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/michi1008/subscriptions",
    "organizations_url": "https://api.github.com/users/michi1008/orgs",
    "repos_url": "https://api.github.com/users/michi1008/repos",
    "events_url": "https://api.github.com/users/michi1008/events{/privacy}",
    "received_events_url": "https://api.github.com/users/michi1008/received_events",
    "type": "User",
    "site_admin": false,
    "name": "michiko lange taguchi",
    "company": null,
    "blog": "",
    "location": "Dublin, CA",
    "email": null,
    "hireable": null,
    "bio": "I am a new coder, but I have a lot of passion for programming and learning new things. I grew up in Japan, but lived in New Zealand and Thailand for a while. ",
    "twitter_username": null,
    "public_repos": 12,
    "public_gists": 0,
    "followers": 1,
    "following": 0,
    "created_at": "2019-06-18T21:29:46Z",
    "updated_at": "2021-08-06T00:18:00Z"
}